### ISSUE TITLE
Interactive rewrite tracker

### ISSUE THREAD

**Issue by rixx** [rixx/books.rixx.de#12]
- [x] /feed.atom, /reviews.atom
- [x] to-read list, or deprecate and remove from index (probably? or sync with calibre …)
- [ ] quotes need to be loaded, too. when?
- [ ] author quotes
- [ ] author pages
- [ ] views for missing data
	- [ ] no page numbers
- [ ] better search / search page
- [x] cover images aren't working
- [ ] tag list page
- [ ] tag detail page
- [ ] thumbnails, oof
- [ ] editor page (behind blockable url, and excluded in debug=false mode)
